# Generated by Django 5.1.2 on 2024-10-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='immediate_joiner',
            new_name='is_immediate_joiner',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements1',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements10',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements2',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements3',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements4',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements5',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements6',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements7',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements8',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements9',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
