# Generated by Django 5.1.2 on 2024-10-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_immediate_joiner_joblisting_is_immediate_joiner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
