# Generated by Django 5.1.2 on 2024-10-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contactus_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_requirements',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='additional_requirements9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
