name: Django CI with React Frontend

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ "node_modules/**/*"]
  pull_request:
    branches: [ "master" ]
    paths-ignore: [ "node_modules/**/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    services:
      mysql:
        image: mysql:latest  # Latest MySQL image
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}            # Use secret for the database name
          MYSQL_USER: ${{ secrets.MYSQL_USER }}                    # Use secret for the database user
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Checkout the codebase
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      # Step 4: Set up Database (MySQL)
      - name: Set up Database
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          python manage.py migrate
        working-directory: Backend

      # Step 5: Run Django Tests
      - name: Run Tests
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          python manage.py test
        working-directory: Backend

      # Step 6: Set up Node.js for the frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 7: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: Frontend
        run: npm install

      # Step 8: Build the Frontend
      - name: Build Frontend
        working-directory: Frontend
        run: |
          CI=false npm run build
