name: Django CI with React Frontend

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ "node_modules/**/*" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore: [ "node_modules/**/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Adjust node versions as per your need
        python-version: [3.8, 3.9]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (This is for the React frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install Node.js dependencies for the frontend
      - name: Install Node.js dependencies
        run: npm install
        working-directory: Frontend  # Make sure this is the correct path to your React frontend

      # Step 4: Build the frontend
      - name: Build the frontend
        run: npm run build
        working-directory: Frontend

      # Step 5: Set up Python (This is for the Django backend)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 6: Install Django dependencies for the backend
      - name: Install Django dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      # Step 7: Run Django tests
      - name: Run Django tests
        run: python manage.py test
        working-directory: Backend
